<h1>Panneau d'administration</h1>
<a href="admin_panel.php" class="btn btn-info">Retour au panneau d'administration</a>
<h2 class="my-5">Rédiger un article</h2>

<form action="add_post.php" method="post" id="add-post-form">
	<!-- Post title -->
	<div class="form-group">
		<label for="title">Titre de l'article :</label>
		<input class="form-control" type="text" for="title" id="addPost-title">
	</div>
	<!-- Post content -->
	<div class="form-group">
		<label for="content">Votre article :</label>
		<textarea class="form-control" type="text" for="content" id="addPost-content"></textarea>
	</div>
	<!-- Post author -->
	<div class="form-group">
		<label for="author">Auteur :</label>
		<select class="custom-select" for="author" id="addPost-author">
			<?php foreach($authors as $author): ?>
				<option value="<?= htmlspecialchars($author['a_id']) ?>"><?= htmlspecialchars($author['a_name']) ?> <?= htmlspecialchars($author['a_surname']) ?></option>
			<?php endforeach; ?>
		</select>
	</div>
	<!-- Post category -->
	<div class="form-group">
		<label for="category">Catégorie :</label>
		<select class="custom-select" for="category" id="addPost-category">
			<?php foreach($categories as $category): ?>
				<option value="<?= htmlspecialchars($category['cat_id']) ?>"><?= htmlspecialchars($category['cat_name']) ?>
				</option>
			<?php endforeach; ?>
		</select>
	</div>
	<!-- Reset and submit button -->
	<div class="text-right">
		<input type="reset" class="btn btn-outline-secondary" value="EFFACER">
		<input type="submit" class="btn btn-success" id="addPost-submit" value="VALIDER">
	</div>
	<!-- Error / validation message -->
	<p class="form-message hidden container bg-warning text-center py-3 mt-3"></p>
</form>