<h2>REDIGER UN ARTICLE</h2>

<form action="add_post.php" method="POST">

	<label for="title" class="labelStyle">Titre de l'article :</label>
	<br>
	<input class="inputStyle" type="text" name="title" for="title">

	<label for="content" class="labelStyle">Votre article :</label>
	<br>
	<textarea class="areaStyle" type="text" name="content" for="content"></textarea>

	<label for="author" class="labelStyle">Auteur :</label>
	<br>
		<select class="selectStyle" name="author" for="author">
			<?php foreach($authors as $author): ?>
				<option value="<?= intval($author['id']) ?>"><?= htmlspecialchars($author['a_name']) ?> <?= htmlspecialchars($author['a_surname']) ?></option>
			<?php endforeach; ?>
		</select>

	<label for="category" class="labelStyle">Catégorie :</label>
	<br>
		<select class="selectStyle" name="category" for="category">
			<?php foreach($categories as $categorie): ?>
				<option value="<?= intval($categorie['id']) ?>"><?= htmlspecialchars($categorie['cat_name']) ?>
				</option>
			<?php endforeach; ?>
		</select>

	<input type="submit" class="valider" value="PUBLIER">
	<input type="reset" class="supprimer" value="EFFACER">

</form>