<?php foreach ($posts as $post): ?>
	<article class="bg-light my-3 p-4">
		<!-- Post title and category -->
		<h2>
			<a href="show_post.php?id=<?= intval($post['p_id']) ?>" class="text-dark">
				<?= htmlspecialchars($post['p_title']) ?>
				<span class="badge badge-pill bg-secondary-light">
					<?= htmlspecialchars($post['cat_name']) ?>
				</span>
			</a>
		</h2>
		<!-- Post creation date/time and author's identity -->
		<p class="subtitle">
			Posté le <?= htmlspecialchars($post['p_creation_date']) ?> par <?= htmlspecialchars($post['a_name'])?> <?= htmlspecialchars($post['a_surname']) ?>
		</p>
		<!-- Post content -->
		<p><?= substr(htmlspecialchars($post['p_content']), 0, 250) ?> [...]</p>
		<!-- Link to the post -->
		<div class="text-right">
			<a href="show_post.php?id=<?= intval($post['p_id']) ?>" class="btn btn-outline-info">Lire la suite</a>
		</div>
	</article>
<?php endforeach; ?>