<h2>PANNEAU D'ADMINISTRATION</h2>
<a href="add_post.php" class="btn-write">Rédiger un article</a>
<h3>Liste des articles publiés</h3>
<table class="m-view admin-table">
	<?php foreach ($posts as $post): ?>
	<tr>
		<td><?= htmlspecialchars($post['p_title']) ?></td>
		<td>
			<a href="edit_post.php?Id=<?= intval($post['id']) ?>">éditer</a>
		</td>
		<td>			
			<a href="delete_post.php?Id=<?= intval($post['id']) ?>">supprimer</a>
		</td> 
	</tr>
	<?php endforeach ?>
</table>
