<ul>
	<?php foreach ($articles as $article): ?>
		<li>			
			<h2>
			<a href="show_post.php?Id=<?= intval($article['Id']) ?>"><?= htmlspecialchars($article['Title']) ?></a>
			</h2>
			<h3>Posté le <span class="boldItalic"><?= htmlspecialchars($article['CreationTimestamp']) ?></span> par <span class="boldItalic"><?= htmlspecialchars($article['FirstName'])?> <?= htmlspecialchars($article['LastName']) ?></span></h3>
			<article class="articleIndex">
				<p><?= substr(htmlspecialchars($article['Contents']), 0, 150) ?>[...]</p>
			</article>
			<a class="valider" href="show_post.php?Id=<?= intval($article['Id']) ?>">Lire la suite</a>
		</li>
		<div class="clear"></div>
	<?php endforeach; ?>
</ul>