<!DOCTYPE html>
<html lang="fr">
<head>
	<meta charset="UTF-8">
	<meta name="robots" content="noindex">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<!-- FontAwesome CSS -->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
	<!-- Google Font -->
	<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet">
	<!-- Custom CSS -->
	<link rel="stylesheet" type="text/css" href="css/custom.css">	
	<!-- Title -->
	<title>Le blog de John Doe</title>
</head>
<body>
	<!-- Header -->
	<header class="mb-3">
		<nav class="navbar navbar-expand-lg bg-info text-uppercase">
			<div class="container">
				<!-- Title -->
				<a href="index.php" class="navbar-brand">John Doe</a>
				<!-- Nav bar collapse button on mobile -->
				<button class="navbar-toggler navbar-dark" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<!-- Nav list -->
				<div id="navbarCollapse" class="collapse navbar-collapse">
					<ul class="navbar-nav ml-auto">
						<!-- If connected -->
						<?php if ($_SESSION['connected'] == true) { ?>
							<li class="nav-item">
								<a href="admin_posts.php" class="nav-link">Articles</a>
							</li>
							<li class="nav-item">
								<a href="admin_panel.php" class="nav-link">Panneau d'administration</a>
							</li>
							<li class="nav-item">
								<a href="deconnection.php" class="nav-link">Déconnexion</a>
							</li>
						<!-- If not connected -->
						<?php } else { ?>
							<li class="nav-item">
								<a href="index.php" class="nav-link">Articles</a>
							</li>
							<li class="nav-item">
								<a href="#" class="nav-link" data-toggle="modal" data-target="#adminModal">Accès admin</a>
							</li>
						<?php } ?>
					</ul>
				</div>
			</div>
		</nav>
		<!-- Connection modal popup (admin access) -->
		<div class="modal fade" id="adminModal" tabindex="-1" role="dialog" aria-hidden="true">
			<div class="modal-dialog modal-dialog-centered" role="document">
				<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title">Veuillez inscrire le mot de passe</h5>
						<button type="button" class="close" data-dismiss="modal" aria-label="Close">
							<span aria-hidden="true">&times;</span>
						</button>
					</div>
					<form action="" method="post">
						<!-- Password input -->
						<div class="modal-body">
							<div class="form-group">
								<input class="form-control" type="password" name="password" autocomplete="off" id="connection-password">
							</div>
						</div>
						<!-- Error message -->
						<div class="form-message hidden container bg-warning text-center py-3 mt-3"></div>
						<!-- Submit button -->
						<div class="modal-footer">
							<button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Annuler</button>
							<input type="submit" id="connection-submit" class="btn btn-success" value="Me connecter">	
						</div>
					</form>
				</div>
			</div>
		</div>
	</header>
	<!-- Main -->
	<main>
		<!-- Aside visible (John Doe's biography) -->
		<?php if (($template != 'admin_panel') && ($template != 'add_post') && ($template != 'edit_post') && ($template != 'forbidden') && ($template != 'session_expired') && ($template != '404')) { ?>
		<div class="container">
			<div class="row">
				<div class="col-12 col-md-8">
					<?php include $template.'.phtml' ?>
				</div>
				<div class="col-4 col-xs-0 d-none d-md-block">
					<img src="img/portrait-johndoe.jpg" alt="Portrait de John Doe" class="img-thumbnail">
					<p class="text-secondary pt-3">Bonjour ! Je suis John Doe, bienvenue sur mon blog ! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi placeat perferendis quam! Accusamus laborum adipisci, nostrum voluptatem laboriosam quam asperiores vero consequatur, suscipit perferendis tempore. Ullam veritatis illo, ab delectus.</p>
				</div>
			</div>
		</div>
		<!-- Aside not visible (John Doe's biography) -->
		<?php } else { ?>
			<div class="container">
				<div class="row">
					<div class="col-12">
						<?php include $template.'.phtml' ?>
					</div>
				</div>
			</div>
		<?php } ?>
	</main>
	<!-- Footer -->
	<footer class="footer bg-dark">
		<div class="container text-center">
			<span class="text-muted">John Doe - 2018</span>
		</div>
	</footer>
	<!-- jQuery -->	
	<script src="http://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
	<!-- Popper.js -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<!-- Bootstrap JS -->
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
	<!-- Custom JS -->
	<script type="text/javascript" src="js/custom.js"></script>
</body>
</html>