<!-- Post -->
<article>
	<!-- Post title -->
	<h2><?= htmlspecialchars($post['p_title']) ?></h2>
	<!-- Post creation date/time and author's identity -->
	<p class="subtitle">
		Posté le <?= htmlspecialchars($post['p_creation_date']) ?> par <?= htmlspecialchars($post['a_name'])?> <?= htmlspecialchars($post['a_surname']) ?>
	</p>
	<!-- Post content -->
	<p><?= $post['p_content'] ?></p>
</article>
<!-- Comments -->
<section class="py-3" id="commentLoop">
	<h4>Commentaires</h4>
	<?php if (empty($comments)): ?>
		<p>Il n'y a pas encore de commentaires.</p>
	<?php endif; ?>
	<ul>
	<?php foreach($comments as $comment): ?>
		<li>
			<p class="subtitle">Posté le <?= htmlspecialchars($comment['com_creation_date']) ?> par <?= htmlspecialchars($comment['com_nickname']) ?></p>
			<p><?= $comment['com_content'] ?></p>
		</li>
	<?php endforeach; ?>
	</ul>
</section>
<!-- Write a comment -->
<section class="pb-3">
	<h4>Rédiger un commentaire</h4>
	<form action="add_comment.php" method="post" id="add-comment-form">
		<!-- Hidden input to link with the post id -->
		<input id="comment-postId" type="hidden" name="Post" method="get" value="<?= intval($_GET['id']) ?>">
		<!-- User nickname -->
		<div class="form-group">
			<label for="com_nickname">Pseudo :</label>
			<input class="form-control" type="text" id="comment-nickname">
		</div>
		<!-- Comment content -->
		<div class="form-group">
			<label for="com_content">Commentaire :</label>
			<textarea class="form-control" id="comment-content" type="textarea"></textarea>
		</div>
		<!-- Error / validation message -->
		<p class="form-message hidden container bg-warning text-center py-3 mt-3"></p>
		<!-- Button submit -->
		<div class="text-right">
			<input class="btn btn-success" type="submit" id="comment-submit" value="VALIDER">
		</div>
	</form>	
</section>